.PHONY: build
build:
	go build -o binarytrees.go_run binarytrees.go
	go build -o binarytrees2.go_run binarytrees2.go
	go build -o binarytrees3.go_run binarytrees3.go
	go build -o binarytrees4.go_run binarytrees4.go
	go build -o binarytrees4_1.go_run binarytrees4_1.go